#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoACOES
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ACOES")]
	public partial class BDLINQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InserttApadrinamiento(tApadrinamiento instance);
    partial void UpdatetApadrinamiento(tApadrinamiento instance);
    partial void DeletetApadrinamiento(tApadrinamiento instance);
    partial void InserttNinio(tNinio instance);
    partial void UpdatetNinio(tNinio instance);
    partial void DeletetNinio(tNinio instance);
    partial void InserttSocio(tSocio instance);
    partial void UpdatetSocio(tSocio instance);
    partial void DeletetSocio(tSocio instance);
    partial void InserttEnvio(tEnvio instance);
    partial void UpdatetEnvio(tEnvio instance);
    partial void DeletetEnvio(tEnvio instance);
    #endregion
		
		public BDLINQDataContext() : 
				base(global::ProyectoACOES.Properties.Settings.Default.ACOESConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BDLINQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDLINQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDLINQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDLINQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tApadrinamiento> tApadrinamiento
		{
			get
			{
				return this.GetTable<tApadrinamiento>();
			}
		}
		
		public System.Data.Linq.Table<tNinio> tNinio
		{
			get
			{
				return this.GetTable<tNinio>();
			}
		}
		
		public System.Data.Linq.Table<tSocio> tSocio
		{
			get
			{
				return this.GetTable<tSocio>();
			}
		}
		
		public System.Data.Linq.Table<tEnvio> tEnvio
		{
			get
			{
				return this.GetTable<tEnvio>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Apadrinamiento")]
	public partial class tApadrinamiento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _socio;
		
		private int _ninio;
		
		private string _agente;
		
		private int _dinero;
		
		private bool _eliminado;
		
		private EntityRef<tNinio> _tNinio;
		
		private EntityRef<tSocio> _tSocio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsocioChanging(int value);
    partial void OnsocioChanged();
    partial void OnninioChanging(int value);
    partial void OnninioChanged();
    partial void OnagenteChanging(string value);
    partial void OnagenteChanged();
    partial void OndineroChanging(int value);
    partial void OndineroChanged();
    partial void OneliminadoChanging(bool value);
    partial void OneliminadoChanged();
    #endregion
		
		public tApadrinamiento()
		{
			this._tNinio = default(EntityRef<tNinio>);
			this._tSocio = default(EntityRef<tSocio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_socio", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int socio
		{
			get
			{
				return this._socio;
			}
			set
			{
				if ((this._socio != value))
				{
					if (this._tSocio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsocioChanging(value);
					this.SendPropertyChanging();
					this._socio = value;
					this.SendPropertyChanged("socio");
					this.OnsocioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ninio", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ninio
		{
			get
			{
				return this._ninio;
			}
			set
			{
				if ((this._ninio != value))
				{
					if (this._tNinio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnninioChanging(value);
					this.SendPropertyChanging();
					this._ninio = value;
					this.SendPropertyChanged("ninio");
					this.OnninioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_agente", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string agente
		{
			get
			{
				return this._agente;
			}
			set
			{
				if ((this._agente != value))
				{
					this.OnagenteChanging(value);
					this.SendPropertyChanging();
					this._agente = value;
					this.SendPropertyChanged("agente");
					this.OnagenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dinero", DbType="Int NOT NULL")]
		public int dinero
		{
			get
			{
				return this._dinero;
			}
			set
			{
				if ((this._dinero != value))
				{
					this.OndineroChanging(value);
					this.SendPropertyChanging();
					this._dinero = value;
					this.SendPropertyChanged("dinero");
					this.OndineroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eliminado", DbType="Bit NOT NULL")]
		public bool eliminado
		{
			get
			{
				return this._eliminado;
			}
			set
			{
				if ((this._eliminado != value))
				{
					this.OneliminadoChanging(value);
					this.SendPropertyChanging();
					this._eliminado = value;
					this.SendPropertyChanged("eliminado");
					this.OneliminadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ninio_Apadrinamiento", Storage="_tNinio", ThisKey="ninio", OtherKey="codigo", IsForeignKey=true)]
		public tNinio tNinio
		{
			get
			{
				return this._tNinio.Entity;
			}
			set
			{
				tNinio previousValue = this._tNinio.Entity;
				if (((previousValue != value) 
							|| (this._tNinio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tNinio.Entity = null;
						previousValue.tApadrinamiento.Remove(this);
					}
					this._tNinio.Entity = value;
					if ((value != null))
					{
						value.tApadrinamiento.Add(this);
						this._ninio = value.codigo;
					}
					else
					{
						this._ninio = default(int);
					}
					this.SendPropertyChanged("tNinio");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Socio_Apadrinamiento", Storage="_tSocio", ThisKey="socio", OtherKey="codigo", IsForeignKey=true)]
		public tSocio tSocio
		{
			get
			{
				return this._tSocio.Entity;
			}
			set
			{
				tSocio previousValue = this._tSocio.Entity;
				if (((previousValue != value) 
							|| (this._tSocio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tSocio.Entity = null;
						previousValue.tApadrinamiento.Remove(this);
					}
					this._tSocio.Entity = value;
					if ((value != null))
					{
						value.tApadrinamiento.Add(this);
						this._socio = value.codigo;
					}
					else
					{
						this._socio = default(int);
					}
					this.SendPropertyChanged("tSocio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ninio")]
	public partial class tNinio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo;
		
		private string _nombre;
		
		private string _apellidos;
		
		private string _estado;
		
		private string _beca;
		
		private string _sexo;
		
		private string _agente;
		
		private System.Nullable<System.DateTime> _fechaNacimiento;
		
		private System.Nullable<System.DateTime> _fechaEntradaAcoes;
		
		private System.Nullable<int> _proyecto;
		
		private System.Nullable<System.DateTime> _fechaEntradaProyecto;
		
		private System.Nullable<System.DateTime> _fechaSalidaProyecto;
		
		private System.Nullable<System.DateTime> _fechaAlta;
		
		private System.Nullable<System.DateTime> _fechaSalidaAcoes;
		
		private string _curso;
		
		private string _comunidadProc;
		
		private string _comunidadAct;
		
		private string _observaciones;
		
		private bool _eliminado;
		
		private EntitySet<tApadrinamiento> _tApadrinamiento;
		
		private EntitySet<tEnvio> _tEnvio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodigoChanging(int value);
    partial void OncodigoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidosChanging(string value);
    partial void OnapellidosChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    partial void OnbecaChanging(string value);
    partial void OnbecaChanged();
    partial void OnsexoChanging(string value);
    partial void OnsexoChanged();
    partial void OnagenteChanging(string value);
    partial void OnagenteChanged();
    partial void OnfechaNacimientoChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaNacimientoChanged();
    partial void OnfechaEntradaAcoesChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaEntradaAcoesChanged();
    partial void OnproyectoChanging(System.Nullable<int> value);
    partial void OnproyectoChanged();
    partial void OnfechaEntradaProyectoChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaEntradaProyectoChanged();
    partial void OnfechaSalidaProyectoChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaSalidaProyectoChanged();
    partial void OnfechaAltaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaAltaChanged();
    partial void OnfechaSalidaAcoesChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaSalidaAcoesChanged();
    partial void OncursoChanging(string value);
    partial void OncursoChanged();
    partial void OncomunidadProcChanging(string value);
    partial void OncomunidadProcChanged();
    partial void OncomunidadActChanging(string value);
    partial void OncomunidadActChanged();
    partial void OnobservacionesChanging(string value);
    partial void OnobservacionesChanged();
    partial void OneliminadoChanging(bool value);
    partial void OneliminadoChanged();
    #endregion
		
		public tNinio()
		{
			this._tApadrinamiento = new EntitySet<tApadrinamiento>(new Action<tApadrinamiento>(this.attach_tApadrinamiento), new Action<tApadrinamiento>(this.detach_tApadrinamiento));
			this._tEnvio = new EntitySet<tEnvio>(new Action<tEnvio>(this.attach_tEnvio), new Action<tEnvio>(this.detach_tEnvio));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidos", DbType="VarChar(100)")]
		public string apellidos
		{
			get
			{
				return this._apellidos;
			}
			set
			{
				if ((this._apellidos != value))
				{
					this.OnapellidosChanging(value);
					this.SendPropertyChanging();
					this._apellidos = value;
					this.SendPropertyChanged("apellidos");
					this.OnapellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(50)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beca", DbType="VarChar(100)")]
		public string beca
		{
			get
			{
				return this._beca;
			}
			set
			{
				if ((this._beca != value))
				{
					this.OnbecaChanging(value);
					this.SendPropertyChanging();
					this._beca = value;
					this.SendPropertyChanged("beca");
					this.OnbecaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				if ((this._sexo != value))
				{
					this.OnsexoChanging(value);
					this.SendPropertyChanging();
					this._sexo = value;
					this.SendPropertyChanged("sexo");
					this.OnsexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_agente", DbType="VarChar(50)")]
		public string agente
		{
			get
			{
				return this._agente;
			}
			set
			{
				if ((this._agente != value))
				{
					this.OnagenteChanging(value);
					this.SendPropertyChanging();
					this._agente = value;
					this.SendPropertyChanged("agente");
					this.OnagenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaNacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> fechaNacimiento
		{
			get
			{
				return this._fechaNacimiento;
			}
			set
			{
				if ((this._fechaNacimiento != value))
				{
					this.OnfechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._fechaNacimiento = value;
					this.SendPropertyChanged("fechaNacimiento");
					this.OnfechaNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaEntradaAcoes", DbType="Date")]
		public System.Nullable<System.DateTime> fechaEntradaAcoes
		{
			get
			{
				return this._fechaEntradaAcoes;
			}
			set
			{
				if ((this._fechaEntradaAcoes != value))
				{
					this.OnfechaEntradaAcoesChanging(value);
					this.SendPropertyChanging();
					this._fechaEntradaAcoes = value;
					this.SendPropertyChanged("fechaEntradaAcoes");
					this.OnfechaEntradaAcoesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proyecto", DbType="Int")]
		public System.Nullable<int> proyecto
		{
			get
			{
				return this._proyecto;
			}
			set
			{
				if ((this._proyecto != value))
				{
					this.OnproyectoChanging(value);
					this.SendPropertyChanging();
					this._proyecto = value;
					this.SendPropertyChanged("proyecto");
					this.OnproyectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaEntradaProyecto", DbType="Date")]
		public System.Nullable<System.DateTime> fechaEntradaProyecto
		{
			get
			{
				return this._fechaEntradaProyecto;
			}
			set
			{
				if ((this._fechaEntradaProyecto != value))
				{
					this.OnfechaEntradaProyectoChanging(value);
					this.SendPropertyChanging();
					this._fechaEntradaProyecto = value;
					this.SendPropertyChanged("fechaEntradaProyecto");
					this.OnfechaEntradaProyectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaSalidaProyecto", DbType="Date")]
		public System.Nullable<System.DateTime> fechaSalidaProyecto
		{
			get
			{
				return this._fechaSalidaProyecto;
			}
			set
			{
				if ((this._fechaSalidaProyecto != value))
				{
					this.OnfechaSalidaProyectoChanging(value);
					this.SendPropertyChanging();
					this._fechaSalidaProyecto = value;
					this.SendPropertyChanged("fechaSalidaProyecto");
					this.OnfechaSalidaProyectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaAlta", DbType="Date")]
		public System.Nullable<System.DateTime> fechaAlta
		{
			get
			{
				return this._fechaAlta;
			}
			set
			{
				if ((this._fechaAlta != value))
				{
					this.OnfechaAltaChanging(value);
					this.SendPropertyChanging();
					this._fechaAlta = value;
					this.SendPropertyChanged("fechaAlta");
					this.OnfechaAltaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaSalidaAcoes", DbType="Date")]
		public System.Nullable<System.DateTime> fechaSalidaAcoes
		{
			get
			{
				return this._fechaSalidaAcoes;
			}
			set
			{
				if ((this._fechaSalidaAcoes != value))
				{
					this.OnfechaSalidaAcoesChanging(value);
					this.SendPropertyChanging();
					this._fechaSalidaAcoes = value;
					this.SendPropertyChanged("fechaSalidaAcoes");
					this.OnfechaSalidaAcoesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_curso", DbType="VarChar(50)")]
		public string curso
		{
			get
			{
				return this._curso;
			}
			set
			{
				if ((this._curso != value))
				{
					this.OncursoChanging(value);
					this.SendPropertyChanging();
					this._curso = value;
					this.SendPropertyChanged("curso");
					this.OncursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comunidadProc", DbType="VarChar(50)")]
		public string comunidadProc
		{
			get
			{
				return this._comunidadProc;
			}
			set
			{
				if ((this._comunidadProc != value))
				{
					this.OncomunidadProcChanging(value);
					this.SendPropertyChanging();
					this._comunidadProc = value;
					this.SendPropertyChanged("comunidadProc");
					this.OncomunidadProcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comunidadAct", DbType="VarChar(50)")]
		public string comunidadAct
		{
			get
			{
				return this._comunidadAct;
			}
			set
			{
				if ((this._comunidadAct != value))
				{
					this.OncomunidadActChanging(value);
					this.SendPropertyChanging();
					this._comunidadAct = value;
					this.SendPropertyChanged("comunidadAct");
					this.OncomunidadActChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observaciones", DbType="VarChar(100)")]
		public string observaciones
		{
			get
			{
				return this._observaciones;
			}
			set
			{
				if ((this._observaciones != value))
				{
					this.OnobservacionesChanging(value);
					this.SendPropertyChanging();
					this._observaciones = value;
					this.SendPropertyChanged("observaciones");
					this.OnobservacionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eliminado", DbType="Bit NOT NULL")]
		public bool eliminado
		{
			get
			{
				return this._eliminado;
			}
			set
			{
				if ((this._eliminado != value))
				{
					this.OneliminadoChanging(value);
					this.SendPropertyChanging();
					this._eliminado = value;
					this.SendPropertyChanged("eliminado");
					this.OneliminadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ninio_Apadrinamiento", Storage="_tApadrinamiento", ThisKey="codigo", OtherKey="ninio")]
		public EntitySet<tApadrinamiento> tApadrinamiento
		{
			get
			{
				return this._tApadrinamiento;
			}
			set
			{
				this._tApadrinamiento.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ninio_Envio", Storage="_tEnvio", ThisKey="codigo", OtherKey="niño")]
		public EntitySet<tEnvio> tEnvio
		{
			get
			{
				return this._tEnvio;
			}
			set
			{
				this._tEnvio.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tApadrinamiento(tApadrinamiento entity)
		{
			this.SendPropertyChanging();
			entity.tNinio = this;
		}
		
		private void detach_tApadrinamiento(tApadrinamiento entity)
		{
			this.SendPropertyChanging();
			entity.tNinio = null;
		}
		
		private void attach_tEnvio(tEnvio entity)
		{
			this.SendPropertyChanging();
			entity.tNinio = this;
		}
		
		private void detach_tEnvio(tEnvio entity)
		{
			this.SendPropertyChanging();
			entity.tNinio = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Socio")]
	public partial class tSocio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo;
		
		private string _nombre;
		
		private string _apellidos;
		
		private string _estado;
		
		private string _nif;
		
		private string _direccion;
		
		private string _poblacion;
		
		private System.Nullable<int> _codigoPostal;
		
		private string _provincia;
		
		private int _tlf;
		
		private System.Nullable<int> _tlfSecundario;
		
		private string _email;
		
		private string _agente;
		
		private string _relacion;
		
		private System.Nullable<bool> _certificado;
		
		private string _sector;
		
		private System.Nullable<System.DateTime> _fechaAlta;
		
		private System.Nullable<System.DateTime> _fechaBaja;
		
		private string _observaciones;
		
		private string _numCuenta;
		
		private bool _eliminado;
		
		private EntitySet<tApadrinamiento> _tApadrinamiento;
		
		private EntitySet<tEnvio> _tEnvio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodigoChanging(int value);
    partial void OncodigoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidosChanging(string value);
    partial void OnapellidosChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    partial void OnnifChanging(string value);
    partial void OnnifChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OnpoblacionChanging(string value);
    partial void OnpoblacionChanged();
    partial void OncodigoPostalChanging(System.Nullable<int> value);
    partial void OncodigoPostalChanged();
    partial void OnprovinciaChanging(string value);
    partial void OnprovinciaChanged();
    partial void OntlfChanging(int value);
    partial void OntlfChanged();
    partial void OntlfSecundarioChanging(System.Nullable<int> value);
    partial void OntlfSecundarioChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnagenteChanging(string value);
    partial void OnagenteChanged();
    partial void OnrelacionChanging(string value);
    partial void OnrelacionChanged();
    partial void OncertificadoChanging(System.Nullable<bool> value);
    partial void OncertificadoChanged();
    partial void OnsectorChanging(string value);
    partial void OnsectorChanged();
    partial void OnfechaAltaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaAltaChanged();
    partial void OnfechaBajaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaBajaChanged();
    partial void OnobservacionesChanging(string value);
    partial void OnobservacionesChanged();
    partial void OnnumCuentaChanging(string value);
    partial void OnnumCuentaChanged();
    partial void OneliminadoChanging(bool value);
    partial void OneliminadoChanged();
    #endregion
		
		public tSocio()
		{
			this._tApadrinamiento = new EntitySet<tApadrinamiento>(new Action<tApadrinamiento>(this.attach_tApadrinamiento), new Action<tApadrinamiento>(this.detach_tApadrinamiento));
			this._tEnvio = new EntitySet<tEnvio>(new Action<tEnvio>(this.attach_tEnvio), new Action<tEnvio>(this.detach_tEnvio));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidos", DbType="VarChar(50)")]
		public string apellidos
		{
			get
			{
				return this._apellidos;
			}
			set
			{
				if ((this._apellidos != value))
				{
					this.OnapellidosChanging(value);
					this.SendPropertyChanging();
					this._apellidos = value;
					this.SendPropertyChanged("apellidos");
					this.OnapellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(50)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nif", DbType="VarChar(50)")]
		public string nif
		{
			get
			{
				return this._nif;
			}
			set
			{
				if ((this._nif != value))
				{
					this.OnnifChanging(value);
					this.SendPropertyChanging();
					this._nif = value;
					this.SendPropertyChanged("nif");
					this.OnnifChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(50)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_poblacion", DbType="VarChar(50)")]
		public string poblacion
		{
			get
			{
				return this._poblacion;
			}
			set
			{
				if ((this._poblacion != value))
				{
					this.OnpoblacionChanging(value);
					this.SendPropertyChanging();
					this._poblacion = value;
					this.SendPropertyChanged("poblacion");
					this.OnpoblacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoPostal", DbType="Int")]
		public System.Nullable<int> codigoPostal
		{
			get
			{
				return this._codigoPostal;
			}
			set
			{
				if ((this._codigoPostal != value))
				{
					this.OncodigoPostalChanging(value);
					this.SendPropertyChanging();
					this._codigoPostal = value;
					this.SendPropertyChanged("codigoPostal");
					this.OncodigoPostalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provincia", DbType="VarChar(50)")]
		public string provincia
		{
			get
			{
				return this._provincia;
			}
			set
			{
				if ((this._provincia != value))
				{
					this.OnprovinciaChanging(value);
					this.SendPropertyChanging();
					this._provincia = value;
					this.SendPropertyChanged("provincia");
					this.OnprovinciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tlf", DbType="Int NOT NULL")]
		public int tlf
		{
			get
			{
				return this._tlf;
			}
			set
			{
				if ((this._tlf != value))
				{
					this.OntlfChanging(value);
					this.SendPropertyChanging();
					this._tlf = value;
					this.SendPropertyChanged("tlf");
					this.OntlfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tlfSecundario", DbType="Int")]
		public System.Nullable<int> tlfSecundario
		{
			get
			{
				return this._tlfSecundario;
			}
			set
			{
				if ((this._tlfSecundario != value))
				{
					this.OntlfSecundarioChanging(value);
					this.SendPropertyChanging();
					this._tlfSecundario = value;
					this.SendPropertyChanged("tlfSecundario");
					this.OntlfSecundarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_agente", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string agente
		{
			get
			{
				return this._agente;
			}
			set
			{
				if ((this._agente != value))
				{
					this.OnagenteChanging(value);
					this.SendPropertyChanging();
					this._agente = value;
					this.SendPropertyChanged("agente");
					this.OnagenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_relacion", DbType="VarChar(50)")]
		public string relacion
		{
			get
			{
				return this._relacion;
			}
			set
			{
				if ((this._relacion != value))
				{
					this.OnrelacionChanging(value);
					this.SendPropertyChanging();
					this._relacion = value;
					this.SendPropertyChanged("relacion");
					this.OnrelacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_certificado", DbType="Bit")]
		public System.Nullable<bool> certificado
		{
			get
			{
				return this._certificado;
			}
			set
			{
				if ((this._certificado != value))
				{
					this.OncertificadoChanging(value);
					this.SendPropertyChanging();
					this._certificado = value;
					this.SendPropertyChanged("certificado");
					this.OncertificadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sector", DbType="VarChar(50)")]
		public string sector
		{
			get
			{
				return this._sector;
			}
			set
			{
				if ((this._sector != value))
				{
					this.OnsectorChanging(value);
					this.SendPropertyChanging();
					this._sector = value;
					this.SendPropertyChanged("sector");
					this.OnsectorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaAlta", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechaAlta
		{
			get
			{
				return this._fechaAlta;
			}
			set
			{
				if ((this._fechaAlta != value))
				{
					this.OnfechaAltaChanging(value);
					this.SendPropertyChanging();
					this._fechaAlta = value;
					this.SendPropertyChanged("fechaAlta");
					this.OnfechaAltaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaBaja", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechaBaja
		{
			get
			{
				return this._fechaBaja;
			}
			set
			{
				if ((this._fechaBaja != value))
				{
					this.OnfechaBajaChanging(value);
					this.SendPropertyChanging();
					this._fechaBaja = value;
					this.SendPropertyChanged("fechaBaja");
					this.OnfechaBajaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observaciones", DbType="VarChar(250)")]
		public string observaciones
		{
			get
			{
				return this._observaciones;
			}
			set
			{
				if ((this._observaciones != value))
				{
					this.OnobservacionesChanging(value);
					this.SendPropertyChanging();
					this._observaciones = value;
					this.SendPropertyChanged("observaciones");
					this.OnobservacionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numCuenta", DbType="VarChar(50)")]
		public string numCuenta
		{
			get
			{
				return this._numCuenta;
			}
			set
			{
				if ((this._numCuenta != value))
				{
					this.OnnumCuentaChanging(value);
					this.SendPropertyChanging();
					this._numCuenta = value;
					this.SendPropertyChanged("numCuenta");
					this.OnnumCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eliminado", DbType="Bit NOT NULL")]
		public bool eliminado
		{
			get
			{
				return this._eliminado;
			}
			set
			{
				if ((this._eliminado != value))
				{
					this.OneliminadoChanging(value);
					this.SendPropertyChanging();
					this._eliminado = value;
					this.SendPropertyChanged("eliminado");
					this.OneliminadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Socio_Apadrinamiento", Storage="_tApadrinamiento", ThisKey="codigo", OtherKey="socio")]
		public EntitySet<tApadrinamiento> tApadrinamiento
		{
			get
			{
				return this._tApadrinamiento;
			}
			set
			{
				this._tApadrinamiento.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Socio_Envio", Storage="_tEnvio", ThisKey="codigo", OtherKey="socio")]
		public EntitySet<tEnvio> tEnvio
		{
			get
			{
				return this._tEnvio;
			}
			set
			{
				this._tEnvio.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tApadrinamiento(tApadrinamiento entity)
		{
			this.SendPropertyChanging();
			entity.tSocio = this;
		}
		
		private void detach_tApadrinamiento(tApadrinamiento entity)
		{
			this.SendPropertyChanging();
			entity.tSocio = null;
		}
		
		private void attach_tEnvio(tEnvio entity)
		{
			this.SendPropertyChanging();
			entity.tSocio = this;
		}
		
		private void detach_tEnvio(tEnvio entity)
		{
			this.SendPropertyChanging();
			entity.tSocio = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Envio")]
	public partial class tEnvio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _remitente;
		
		private int _niño;
		
		private int _socio;
		
		private string _etiqueta;
		
		private EntityRef<tNinio> _tNinio;
		
		private EntityRef<tSocio> _tSocio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnremitenteChanging(string value);
    partial void OnremitenteChanged();
    partial void OnniñoChanging(int value);
    partial void OnniñoChanged();
    partial void OnsocioChanging(int value);
    partial void OnsocioChanged();
    partial void OnetiquetaChanging(string value);
    partial void OnetiquetaChanged();
    #endregion
		
		public tEnvio()
		{
			this._tNinio = default(EntityRef<tNinio>);
			this._tSocio = default(EntityRef<tSocio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remitente", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string remitente
		{
			get
			{
				return this._remitente;
			}
			set
			{
				if ((this._remitente != value))
				{
					this.OnremitenteChanging(value);
					this.SendPropertyChanging();
					this._remitente = value;
					this.SendPropertyChanged("remitente");
					this.OnremitenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_niño", DbType="Int NOT NULL")]
		public int niño
		{
			get
			{
				return this._niño;
			}
			set
			{
				if ((this._niño != value))
				{
					if (this._tNinio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnniñoChanging(value);
					this.SendPropertyChanging();
					this._niño = value;
					this.SendPropertyChanged("niño");
					this.OnniñoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_socio", DbType="Int NOT NULL")]
		public int socio
		{
			get
			{
				return this._socio;
			}
			set
			{
				if ((this._socio != value))
				{
					if (this._tSocio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsocioChanging(value);
					this.SendPropertyChanging();
					this._socio = value;
					this.SendPropertyChanged("socio");
					this.OnsocioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etiqueta", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string etiqueta
		{
			get
			{
				return this._etiqueta;
			}
			set
			{
				if ((this._etiqueta != value))
				{
					this.OnetiquetaChanging(value);
					this.SendPropertyChanging();
					this._etiqueta = value;
					this.SendPropertyChanged("etiqueta");
					this.OnetiquetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ninio_Envio", Storage="_tNinio", ThisKey="niño", OtherKey="codigo", IsForeignKey=true)]
		public tNinio tNinio
		{
			get
			{
				return this._tNinio.Entity;
			}
			set
			{
				tNinio previousValue = this._tNinio.Entity;
				if (((previousValue != value) 
							|| (this._tNinio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tNinio.Entity = null;
						previousValue.tEnvio.Remove(this);
					}
					this._tNinio.Entity = value;
					if ((value != null))
					{
						value.tEnvio.Add(this);
						this._niño = value.codigo;
					}
					else
					{
						this._niño = default(int);
					}
					this.SendPropertyChanged("tNinio");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Socio_Envio", Storage="_tSocio", ThisKey="socio", OtherKey="codigo", IsForeignKey=true)]
		public tSocio tSocio
		{
			get
			{
				return this._tSocio.Entity;
			}
			set
			{
				tSocio previousValue = this._tSocio.Entity;
				if (((previousValue != value) 
							|| (this._tSocio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tSocio.Entity = null;
						previousValue.tEnvio.Remove(this);
					}
					this._tSocio.Entity = value;
					if ((value != null))
					{
						value.tEnvio.Add(this);
						this._socio = value.codigo;
					}
					else
					{
						this._socio = default(int);
					}
					this.SendPropertyChanged("tSocio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
